---
title: "Ada malnutrition report"
author: "Healthmates Nutrition"
date: "8/28/2021"
institute: "Healthmates Nutrition Limited"
output:
  html_document:
    toc: true
    toc_float: true
  css: "bootstrap.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

```{r import, echo=FALSE}
# Importing packages for project

pacman::p_load (
        tidyverse, # Data management
        rio, # Importing dataset
        here, # Working directory
        janitor, # Clean data names
        googlesheets4, # Read sheets from Google sheets
        gtsummary, # Create summary tables
        skimr, # Overview of dataset
        GGally, # Correlation matrix
        tinytex, # Creating pdf documents
        finalfit # Creating models
        
        
)
```


```{r import-dataset, include=FALSE}
ada <- read_sheet("https://docs.google.com/spreadsheets/d/1rkdOdIxIrAXuedT_4bbHxyxWgoa6l4yUxbBuwX6FxNE/edit?usp=sharing",
                 
                 range = "Sheet1!A2:AB77",# Read column A2 to AB77
                  
                  # Modify column names
                 
                  col_names = c("start-time",
                                "end-time",
                                "today",
                                "name",
                                "dob",
                                "age_mons",
                                "display_age",
                                "age_manual",
                                "sex",
                                "age_mother",
                                "marital_status",
                                "educ_mum",
                                "occupation_mum",
                                "other_occupation",
                                "num-child",
                                "income",
                                "breasfeed_child",
                                "duration_bf",
                                "hours_bf",
                                "day_bf",
                                "age_intro_feed",
                                "average_intake",
                                "bwt",
                                "wt",
                                "lenhei",
                                "head_circumference",
                                "muac",
                                "edema"),
                 
                 col_types = "???c?i?icicccciccciciinnnnnc")
                  


```




```{r}
# Export sheet data into csv

export (ada, here ("data", "ada_full.csv"))
```


```{r}
# Children less or equal to five

ada_five<- ada %>% filter (age_mons <= 60 | age_manual <=60)

```


```{r}
# Children greater than five years

ada_nine<- ada %>% filter (age_mons > 60 | age_manual > 60)
```


```{r}
# Export five year or less dataset

export (ada_five, here("data","ada_five_final.csv"))
```


```{r}
# Export dataset for children older than five years

export (ada_nine, here("data","ada_nine_final.csv"))
```



```{r}
ff_glimpse(ada)

missing_glimpse(ada)
```


## Data wrangling

```{r ada-five-wrangling}
ada_five<- ada_five%>%
        mutate (
                sex = factor(sex)%>%
                        fct_recode("Male" = "1",
                                   "Female" = "2")%>%
                        ff_label("Sex"),
                
                marital_status = factor(marital_status)%>%
                        fct_recode("Married" = "1",
                                   "Single" = "2",
                                   "Separated/Divorced" = "3",
                                   "Cohabiting" = "4")%>%
                        ff_label("Marital status"),
                
                educ_mum = factor(educ_mum)%>%
                        fct_recode("Never attended school" = "1",
                                   "Elementary/Primary" = "2",
                                   "Junior High" = "3",
                                   "Senior High" = "4",
                                   "Tertiary" = "5")%>%
                        ff_label("Educational status"),
                
                occupation_mum = factor(occupation_mum)%>%
                        fct_recode("Farmer" = "1",
                                   "Trader" = "2",
                                   "Dressmaker" = "3",
                                   "Hairdresser" = "4",
                                   "Others" = "5")%>%
                        ff_label("Occupation"),
                
                income = factor(income)%>%
                        fct_recode("Less than 500 cedis"="1",
                                   "500-900 cedis" = "2",
                                   "1000-1500 cedis" = "3",
                                   "1500 cedis" = "4")%>%
                        ff_label("Income"),
                
                breastfeed_child = factor(breasfeed_child)%>%
                        fct_recode("No"="0",
                                   "Yes" = "1",
                                   "Don't know" = "9")%>%
                        ff_label("Breastfeed"),
                
                duration_bf = factor(duration_bf)%>%
                        fct_recode("Immediately" = "1",
                                   "Within first hour" = "2",
                                   "Hours" = "3",
                                   "Don't know" = "9")%>%
                        ff_label("Duration of breastfeeding"),
                
                day_bf = factor (day_bf)%>%
                        fct_recode("No" = "0",
                                   "Yes" = "1",
                                   "Don't know" = "9")%>%
                        ff_label("Breastfed the day before survey"),
                
                age_intro_feed = factor (age_intro_feed)%>%
                        fct_recode("<= 2 months" = "1",
                                   "3 months" = "2",
                                   "4 months" = "3",
                                   "5 months" = "4",
                                   "6 months" = "5",
                                   "> 6 months" = "6",
                                   "Don't know" = "9")%>%
                        ff_label("Age of introducing complementary meals"),
                
                edema = factor(edema)%>%
                        fct_recode("No" = "0",
                                   "Yes"= "1")%>%
                        ff_label("Edema")
                        
                
                                   )




```


```{r ada-nine-wrangling}
ada_nine<- ada_nine%>%
        mutate (
                sex = factor(sex)%>%
                        fct_recode("Male" = "1",
                                   "Female" = "2")%>%
                        ff_label("Sex"),
                
                marital_status = factor(marital_status)%>%
                        fct_recode("Married" = "1",
                                   "Single" = "2",
                                   "Separated/Divorced" = "3",
                                   "Cohabiting" = "4")%>%
                        ff_label("Marital status"),
                
                educ_mum = factor(educ_mum)%>%
                        fct_recode("Never attended school" = "1",
                                   "Elementary/Primary" = "2",
                                   "Junior High" = "3",
                                   "Senior High" = "4",
                                   "Tertiary" = "5")%>%
                        ff_label("Educational status"),
                
                occupation_mum = factor(occupation_mum)%>%
                        fct_recode("Farmer" = "1",
                                   "Trader" = "2",
                                   "Dressmaker" = "3",
                                   "Hairdresser" = "4",
                                   "Others" = "5")%>%
                        ff_label("Occupation"),
                
                income = factor(income)%>%
                        fct_recode("Less than 500 cedis"="1",
                                   "500-900 cedis" = "2",
                                   "1000-1500 cedis" = "3",
                                   "1500 cedis" = "4")%>%
                        ff_label("Income"),
                
                breastfeed_child = factor(breasfeed_child)%>%
                        fct_recode("No"="0",
                                   "Yes" = "1",
                                   "Don't know" = "9")%>%
                        ff_label("Breastfeed"),
                
                duration_bf = factor(duration_bf)%>%
                        fct_recode("Immediately" = "1",
                                   "Within first hour" = "2",
                                   "Hours" = "3",
                                   "Don't know" = "9")%>%
                        ff_label("Duration of breastfeeding"),
                
                day_bf = factor (day_bf)%>%
                        fct_recode("No" = "0",
                                   "Yes" = "1",
                                   "Don't know" = "9")%>%
                        ff_label("Breastfed the day before survey"),
                
                age_intro_feed = factor (age_intro_feed)%>%
                        fct_recode("<= 2 months" = "1",
                                   "3 months" = "2",
                                   "4 months" = "3",
                                   "5 months" = "4",
                                   "6 months" = "5",
                                   "> 6 months" = "6",
                                   "Don't know" = "9")%>%
                        ff_label("Age of introducing complementary meals"),
                
                edema = factor(edema)%>%
                        fct_recode("No" = "0",
                                   "Yes"= "1")%>%
                        ff_label("Edema")
                        
                
                                   )
```


## Exploratory data analysis




## Visualisations



## Conclusion


